In [2]:
import numpy as np

In [3]:
# COPY

In [4]:
arr=np.array([1,2,3,4,5,6,7])
newarr=arr.copy()
arr

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
newarr[0]=9
newarr

array([9, 2, 3, 4, 5, 6, 7])

In [6]:
# VIEW

In [7]:
arr=np.array([1,2,3,4,5,6,7])
newarr=arr.view()
arr

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
newarr[0]=9
newarr

array([9, 2, 3, 4, 5, 6, 7])

In [9]:
arr

array([9, 2, 3, 4, 5, 6, 7])

In [10]:
# Shape

In [11]:
arr=np.array([[2,3,4],[7,8,9]])
arr.shape

(2, 3)

In [ ]:
# RESHAPE

In [ ]:
arr=np.array([10,20,30,40]).reshape(2,2)
print(arr)

In [ ]:
# Arange

In [ ]:
arr=np.arange(1,15)
arr

In [ ]:
arr=np.arange(1,15,2)
arr

In [ ]:
# LINSPACE

In [ ]:
arr=np.linspace(1,5,2)
arr

In [ ]:
# CONCATENATE

In [ ]:
arr1=np.array([5,6,7])
arr2=np.array([8,9,10])
res=np.concatenate((arr1,arr2))
res

In [ ]:
arr1=np.array([[10,11,12],[13,14,15]])
arr2=np.array([[16,17,18],[19,20,21]])
res=np.concatenate((arr1,arr2),axis=1)
res


In [ ]:
# ARITHMETIC OPERATION


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
arr1+arr2


In [ ]:
arr1=np.array([11,12,13])
arr2=np.array([14,15,16])
arr1*arr2

In [ ]:
arr1=np.array([2,3,4])
arr2=np.array([5,6,7])
arr1/arr2