In [1]:
import numpy

In [2]:
import numpy as np


In [3]:
#zero dimensitional


In [4]:
#One dimensional


In [5]:
one_dim=np.array([1,3,5,7,15,19])
print("dim",one_dim.ndim)
print("index",one_dim[2])
#slicing
print(one_dim[1:4])
#negative slicing
print(one_dim[-3:])

dim 1
index 5
[3 5 7]
[ 7 15 19]


In [6]:
#Two dimensional

In [7]:
two_dim=np.array([[1,2,3],[4,5,6]])
print("dim",two_dim.ndim)
print("index",two_dim[0,1])
print("index",two_dim[1,0])
#slicing
print(two_dim[0,1])
#negative
print("index",two_dim[1,-2])      

dim 2
index 2
index 4
2
index 5


In [8]:
#Three dimensional

In [9]:
three_dim=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("dim",three_dim.ndim)
print("index",three_dim[0,1,0])
print("index",three_dim[1,1,0])
#slicing
print(three_dim[0,0,1])
#negative
print("index",three_dim[0,-1,0])

dim 3
index 4
index 10
2
index 4


In [10]:
#zeros

In [11]:
zero_arr=np.zeros((2,2))
zero_arr

array([[0., 0.],
       [0., 0.]])

In [12]:
#ones

In [13]:
one_arr=np.ones((4,3))
one_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
#full

In [15]:
full_arr=np.full((2,2),5)
full_arr

array([[5, 5],
       [5, 5]])