## Join

In [1]:
import numpy as np

In [2]:
arr1=np.array([11,12,13,14,15])
arr2=np.array([16,17,18,19,20])
res=np.concatenate((arr1,arr2),axis=0)
res

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Stack

In [3]:
res=np.stack((arr1,arr2),axis=1)
res

array([[11, 16],
       [12, 17],
       [13, 18],
       [14, 19],
       [15, 20]])

In [4]:
res=np.hstack((arr1,arr2))
res

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
res=np.vstack((arr1,arr2))
res

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [6]:
res=np.dstack((arr1,arr2))
res

array([[[11, 16],
        [12, 17],
        [13, 18],
        [14, 19],
        [15, 20]]])

## Split

In [8]:
arr=np.array([1,2,3,4,5,6,7,8])
new_arr=np.split(arr,2)
new_arr

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [9]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
new_array=np.array_split(arr1,3)
new_array

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]