In [6]:
#LOOPING

In [7]:
import numpy as np

In [8]:
arr=np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [9]:
arr1=np.array([[1,2,3],[4,5,6]])
for i  in arr1:
  print(i)

[1 2 3]
[4 5 6]


In [10]:
for i in arr1:
    for j in i:
        print(j)

1
2
3
4
5
6


In [11]:
for i in np.nditer(arr1):
  print(i)

1
2
3
4
5
6


In [12]:
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr2:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [13]:
for i in arr2:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [14]:
for i in np.nditer(arr2):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [15]:
arr=np.array([10,11,12])
arr.dtype

dtype('int64')

In [16]:
for i in np.nditer(arr,flags=["buffered"],op_dtypes=["S"]):
    print(i)

np.bytes_(b'10')
np.bytes_(b'11')
np.bytes_(b'12')


In [17]:
#enumerate

In [18]:
for i in np.ndenumerate(arr):
    print(i)

((0,), np.int64(10))
((1,), np.int64(11))
((2,), np.int64(12))


In [19]:
for i,j in np.ndenumerate(arr):
    print(i,j)
 

(0,) 10
(1,) 11
(2,) 12


In [20]:
#SORTING

In [21]:
arr=np.array([2,4,5,1,8,10,3,15,0])
sorted=np.sort(arr)
sorted

array([ 0,  1,  2,  3,  4,  5,  8, 10, 15])

In [22]:
# arg sort

In [23]:
arr1=np.array([7,8,9,10])
indices=np.argsort(arr1)
arr2=np.array(["A","B","C","D"])
sorted=arr2[indices]
sorted


array(['A', 'B', 'C', 'D'], dtype='<U1')

In [24]:
#inplace

In [25]:
arr=np.array([55,20,2,45,-5,0,-4,9])

In [26]:
arr.sort()
arr

array([-5, -4,  0,  2,  9, 20, 45, 55])

In [27]:
# Datatypes

In [28]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [30]:
arr=np.array(["rose","yellow"])
print(arr.dtype)

<U6


In [32]:
# Creating array with defined datatypes

In [35]:
arr=np.array([1,2,3,4],dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [37]:
# Convert Dtatypes on existing array

In [41]:
arr=np.array([1.2,3.5,9.5])
newarr=arr.astype("i")
print(newarr)
print(newarr.dtype)

[1 3 9]
int32


In [43]:
arr=np.array([1.2,5.4,5.9])
newarr=arr.astype(int)
print(newarr.dtype)

int64


In [48]:
arr=np.array([2,3,5,0])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True  True False]
bool
