In [25]:
import numpy as np
from numpy import random

In [26]:
# create an array of 10 zeros
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
# create an array of 10 ones
arr=np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
# create an array of 10 fives
arr=np.full(10,5)
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [29]:
# create an array of the intergers from 10 to 50
arr=np.arange(10,51)
arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [30]:
# create an array of all the even integers from 10 to 50
arr=np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [31]:
# create a 3*3 matrix with values ranging from 0 to 8
arr1=np.arange(0,9).reshape(3,3)
arr1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
# create a 3*3 identity matrix
arr=np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# use numpy to generate a random number between 0 and 1
arr=random.rand(1)
arr


array([0.14249897])

In [51]:
# use numpy to generate an array of 25 random numbers sampled from a standard normal distribution
arr=np.random.normal(0,1,25)
arr

array([ 1.62801549,  0.94602231, -0.67003079,  1.31110145,  0.03911701,
       -1.21794992, -1.19393319,  0.37622602,  0.1741196 , -0.17891085,
       -0.63777227,  0.24578381,  1.94267998, -0.19243123,  1.48346745,
       -0.09131708, -0.22727179, -1.26846813, -1.59701549, -1.48700678,
        0.15430939,  0.38253092, -0.71779352, -1.42471926, -0.12656496])

In [54]:
# create  the following matrix
arr=np.arange(1,101).reshape(10,10)/100
arr


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [49]:
# create of array of 20 linearly spaced points between 0 and 1
arr=np.linspace(0,1,20)
arr


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing And Selection

In [37]:
mat=np.arange(1,26).reshape(5,5)
mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:

arr=np.arange(12,26).reshape(-1)
res=np.array(
   [ arr[0:4],arr[5:9],arr[10:14]]
)
res

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [39]:
arr=np.array(20)
arr

array(20)

In [40]:
arr=np.array([21,22,23,24,25])
arr

array([21, 22, 23, 24, 25])

In [56]:
mat[0:3,1:2]
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
arr=np.array([[16,17,18,19,20],[21,22,23,24,25]])
arr

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Do the following

In [42]:
# Get the sum of all the values in matrix

In [43]:
mat.sum()

np.int64(325)

In [44]:
# Get the Standard deviation of the values in mat

In [45]:
mat.std()

np.float64(7.211102550927978)

In [46]:
# Get the sum of all the columns in mat

In [47]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])