# statistical function

In [2]:
import numpy as np

In [ ]:
# SORT

In [3]:
arr1=np.array([10,11,12,13,14,15])
arr1.sort()
arr1

array([10, 11, 12, 13, 14, 15])

In [ ]:
# MEDIAN

In [4]:
median_value=np.median(arr1)
median_value


np.float64(12.5)

In [5]:
std_value=np.std(arr1)
std_value

np.float64(1.707825127659933)

In [6]:
min_value=np.min(arr1)
min_value

np.int64(10)

In [7]:
# RANGE

In [8]:
range_value=np.ptp(arr1)
range_value

np.int64(5)

In [9]:
# PERCENTILE

In [10]:
percentile_30th=np.percentile(arr1,30)
percentile_30th

np.float64(11.5)

In [11]:
# PRODUCT

In [12]:
product=np.prod(arr1)
product

np.int64(3603600)

In [13]:
cum_sum=np.cumsum(arr1)
cum_sum

array([10, 21, 33, 46, 60, 75])

In [14]:
cum_product=np.cumprod(arr1)
cum_product

array([     10,     110,    1320,   17160,  240240, 3603600])

In [15]:
# UNIQUE ELEMENTS

In [16]:
element,count =np.unique(arr1,return_counts=True)
element


array([10, 11, 12, 13, 14, 15])

In [17]:
count

array([1, 1, 1, 1, 1, 1])

In [18]:
# Boolean operation

In [27]:
bool_arr=arr1>13
bool_arr

array([False, False, False, False,  True,  True])

In [ ]:
# filter array

In [26]:
arr=np.array([15,16,17,18])
x=[True,True,True,False]
newarr=arr[x]
newarr

array([15, 16, 17])

In [25]:
Aarr=np.array([1,2,3,4])
x=[True,False,False,False]
newarr=arr[x]
newarr

array([15])

In [31]:
filtered_data=arr1[bool_arr]
filtered_data

array([14, 15])